name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main  # Adjust this to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'  # Specify the Node version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Verify dist folder contents
        run: ls -la dist

      - name: Create public folder if it does not exist
        run: mkdir -p public

      - name: Copy build files into public
        run: cp -R dist/* public/

      - name: Verify public folder contents after copy
        run: ls -la public

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live  # Set to 'live' or another channel if using preview channels
          projectId: "your-firebase-project-id"  # Replace with your Firebase Project ID
